version: 0.1

phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies
      - npm install
      - npm test
  build:
    commands:
      - echo Build started on 'date'
      - npm run build
  post_build:
    commands:
      - echo Post build stage here

artifacts:
  files:
    - index.html
    - favicon.ico
    - styles/main.css
    - images/*
    - dist/bundle.js
